# Generated by Django 6.0 on 2026-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quest_battlepass_userquestprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='reward_chips',
            field=models.IntegerField(default=0),
        ),
    ]
