# Generated by Django 6.0.4 on 2026-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quest_reward_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepass',
            name='claimed_rewards',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=20),
        ),
    ]
