# Generated by Django 6.0 on 2026-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_battlepass_claimed_rewards_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('neon', 'Neon'), ('gold', 'Gold'), ('retro', 'Retro Vegas'), ('minimal', 'Minimal')], default='neon', max_length=20),
        ),
    ]
