# Generated by Django 5.2.13 on 2026-05-03 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_buy_in', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('max_buy_in', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('active', 'Game in progress'), ('completed', 'Game completed')], default='waiting', max_length=20)),
                ('current_hand_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_poker_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PokerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_in_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.pokergame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PokerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.IntegerField()),
                ('community_cards', models.JSONField(default=list)),
                ('pot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pre-flop', 'Pre-Flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('completed', 'Completed')], default='pre-flop', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='main.pokergame')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealt_hands', to='main.pokerplayer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_hands', to='main.pokerplayer')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_cards', models.JSONField(default=list)),
                ('current_bet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_folded', models.BooleanField(default=False)),
                ('is_all_in', models.BooleanField(default=False)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_hands', to='main.pokerhand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pokerplayer')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('fold', 'Fold'), ('check', 'Check'), ('call', 'Call'), ('bet', 'Bet'), ('raise', 'Raise'), ('all_in', 'All In')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='main.pokerhand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pokerplayer')),
            ],
        ),
    ]
