# Generated by Django 5.2.13 on 2026-05-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pokergame_pokerplayer_pokerhand_playerhand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerhand',
            name='current_player_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='main.pokerplayer'),
        ),
    ]
