# Generated by Django 5.2.13 on 2026-05-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pokerhand_current_player_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerhand',
            name='current_round_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pokerhand',
            name='players_acted_this_round',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pokerhand',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
    ]
