# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pokerhand_current_round_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestprogress',
            name='cycle_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
