# Generated by Django 5.2.13 on 2026-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userquestprogress_cycle_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokergame',
            name='big_blind',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pokergame',
            name='small_blind',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
