# Generated by Django 5.2.13 on 2026-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pokergame_big_blind_pokergame_small_blind'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerhand',
            name='players_ready',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pokerhand',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for ready'), ('pre-flop', 'Pre-Flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
