# Generated by Django 5.2.13 on 2026-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pokerhand_players_ready_alter_pokerhand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerhand',
            name='deck',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokerhand',
            name='next_card_index',
            field=models.IntegerField(default=0),
        ),
    ]
