# Generated by Django 5.2.13 on 2026-05-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pokerhand_deck_pokerhand_next_card_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerhand',
            name='big_blind_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_blind_hands', to='main.pokerplayer'),
        ),
        migrations.AddField(
            model_name='pokerhand',
            name='small_blind_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_blind_hands', to='main.pokerplayer'),
        ),
    ]
